export const ingredientEmojis = {
  'manzana': '🍎',
  'platano': '🍌',
  'uvas': '🍇',
  'sandia': '🍉',
  'limon': '🍋',
  'fresa': '🍓',
  'durazno': '🍑',
  'piña': '🍍',
  'aguacate': '🥑',
  'tomate': '🍅',
  'berenjena': '🍆',
  'zanahoria': '🥕',
  'maiz': '🌽',
  'papa': '🥔',
  'pan': '🍞',
  'queso': '🧀',
  'huevo': '🥚',
  'tocino': '🥓',
  'pollo': '🍗',
  'carne': '🍖',
  'pescado': '🐟',
  'camarones': '🦐',
  'langosta': '🦞',
  'sushi': '🍣',
  'arroz': '🍚',
  'espagueti': '🍝',
  'helado': '🍦',
  'pastel': '🍰',
  'chocolate': '🍫',
  'caramelo': '🍬',
  'miel': '🍯',
  'cerveza': '🍺',
  'vino': '🍷',
  'cafe': '☕',
  'te': '🍵',
  'leche': '🥛',
  'agua': '💧',
  'cacahuate': '🥜',
  'croissant': '🥐',
  'hamburguesa': '🍔',
  'pizza': '🍕',
  'hotdog': '🌭',
  'sandwich': '🥪',
  'taco': '🌮',
  'burrito': '🌯',
  'ensalada': '🥗',
  'palomitas': '🍿',
  'donut': '🍩',
  'galleta': '🍪',
  'cerezas': '🍒',
  'mango': '🥭',
  'coco': '🥥',
  'kiwi': '🥝',
  'cacahuates': '🥜',
  'miel_pot': '🍯',
  'sake': '🍶',
  'champagne': '🍾',
  'copas': '🍷',
  'coctel': '🍸',
  'bebida_tropical': '🍹',
  'cervezas': '🍻',
  'copas_chocando': '🥂',
  'vaso': '🥃',
  'vaso_con_paja': '🥤',
  'palillos': '🥢',
  'cuchillo': '🔪',
  'cuchara': '🥄',
  'tenedor': '🍴',
  'plato': '🍽️',
  'taza': '🍵',
  'taza_con_popote': '🥤',
  'taza_con_tapa': '☕',
  'taza_de_te': '🍵',
  'sal': '🧂',
  'chile': '🌶️',
  'aceite': '🫒'
};


export function getEmoji(ingredient) {
  ingredient = ingredient.toLowerCase().replace(/ /g, '_');
  // si no tenemos el emoji, probamos solo con la palabra antes del _
  if (!ingredientEmojis[ingredient]) {
    ingredient = ingredient.split('_')[0];
  }
  return ingredientEmojis[ingredient] || '🔪';
}