name: Slack Notification

on:
  push:
    branches: [ "release/v0.1" ]
  pull_request:
    branches: [ "release/v0.1" ]


jobs:
  slack_notification:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Send Slack notification
      run: |
        curl -X POST -H 'Content-type: application/json' \
        --data '{"text":"Build successful!"}' \
        https://hooks.slack.com/services/sytw/GgiUiOJJeifKY0uamYUGF1Zr#04